version: "3.5"

services:    
  postgres:
    build:
      context: .
      dockerfile: ./DockerPostgresql
    environment:
      POSTGRES_DB: "project"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data/
    ports:
      - "6666:5432"
    restart: always
    networks:
      - my_network

  mongo:
    image: mongo:4.4.18
    # image: mongo
    restart: always
    ports:
      - '6000:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: '12345'
    volumes:
      - ../mongodb:/data/db
    networks:
        - my_network

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 6001:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: '12345'
  #     ME_CONFIG_MONGODB_URL: mongodb://root:12345@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #     networks:
  #       - my_network

  python:
    build:
      context: .
      dockerfile: ./PythonDockerFile
    volumes:
      - ..:/usr/telegarm_bot/
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge